using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;

#if UNITY_EDITOR
public class GenerateGGXIblSamples
{
    // 配置参数：与 Unity 核心管线标准一致
    private const int MIP_LEVEL_COUNT = 7; // 循环范围 1 到 6，对应实际 mip index 0-5
    private const int SAMPLES_PER_LEVEL = 34;
    private const int UNITY_SPECCUBE_LOD_STEPS = 6;

    // 输出贴图的文件名
    private const string OUTPUT_PATH = "Assets/GGX_IBL_LUT.exr";

    [MenuItem("Tools/Generate GGX IBL Samples (Code + Texture)")]
    public static void Generate()
    {
        // 1. 准备字符串构建器 (用于生成 HLSL 数组)
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Generated by C# Script");
        sb.AppendLine("// Format: float4(localL.x, localL.y, localL.z, omegaS)");
        sb.AppendLine($"// {MIP_LEVEL_COUNT - 1} mip levels * {SAMPLES_PER_LEVEL} samples = {(MIP_LEVEL_COUNT - 1) * SAMPLES_PER_LEVEL} elements");
        sb.AppendLine("static const float4 k_GGXIblSamples[] = {");

        // 2. 准备纹理 (宽度=样本数, 高度=Mip层级数)
        // 使用 RGBAFloat 确保精度，Linear 空间
        Texture2D lutTexture = new Texture2D(SAMPLES_PER_LEVEL, MIP_LEVEL_COUNT - 1, TextureFormat.RGBAFloat, false, true);
        lutTexture.filterMode = FilterMode.Point;
        lutTexture.wrapMode = TextureWrapMode.Clamp;

        // --- 开始遍历 ---
        // 遍历 Mip Level (1 到 6，对应输出的 index 0 到 5)
        for (int mip = 1; mip < MIP_LEVEL_COUNT; mip++)
        {
            int arrayMipIndex = mip - 1; // 0 to 5
            
            float perceptualRoughness = MipmapLevelToPerceptualRoughness(mip);
            float roughness = PerceptualRoughnessToRoughness(perceptualRoughness);

            sb.AppendLine($"\n    // --- Mip Level {arrayMipIndex} (PerceptualRoughness: {perceptualRoughness:F4}) ---");

            for (int i = 0; i < SAMPLES_PER_LEVEL; i++)
            {
                // A. 计算逻辑
                // 1. 生成 Fibonacci 均匀分布点
                Vector2 u = Fibonacci2d(i, SAMPLES_PER_LEVEL);

                // 2. 计算 GGX 重要性采样方向
                Vector3 localL;
                float NdotL, NdotH, LdotH;
                SampleGGXDir(u, roughness, out localL, out NdotL, out NdotH, out LdotH);

                // 3. 计算 OmegaS
                float omegaS = ComputeOmegaS(NdotH, roughness, SAMPLES_PER_LEVEL);

                // B. 填充字符串数据
                string line = string.Format("    float4({0:F6}, {1:F6}, {2:F6}, {3:F8}), // Sample {4}",
                    localL.x, localL.y, localL.z, omegaS, i);
                sb.AppendLine(line);

                // C. 填充纹理数据
                // x = sample index, y = mip level index
                // 注意：LocalL 可能包含负数，EXR 格式支持负值
                Color pixelColor = new Color(localL.x, localL.y, localL.z, omegaS);
                lutTexture.SetPixel(i, arrayMipIndex, pixelColor);
            }
        }
        sb.AppendLine("};");

        // --- 收尾工作 ---

        // 1. 应用纹理修改并保存为 EXR
        lutTexture.Apply();
        byte[] bytes = lutTexture.EncodeToEXR(Texture2D.EXRFlags.OutputAsFloat);
        File.WriteAllBytes(OUTPUT_PATH, bytes);
        Object.DestroyImmediate(lutTexture);

        // 2. 刷新 AssetDatabase 以加载新文件
        AssetDatabase.Refresh();

        // 3. 自动设置纹理导入设置 (确保它是纯数据，不被色彩校正)
        SetTextureImporterSettings(OUTPUT_PATH);

        // 4. 复制文本到剪贴板
        GUIUtility.systemCopyBuffer = sb.ToString();

        // 5. 提示完成
        EditorUtility.DisplayDialog("Success", 
            $"生成完成！\n\n1. 数组代码已复制到剪贴板。\n2. 贴图已保存至: {OUTPUT_PATH}", 
            "OK");
    }

    // --- 纹理导入设置自动配置 ---
    static void SetTextureImporterSettings(string path)
    {
        TextureImporter importer = AssetImporter.GetAtPath(path) as TextureImporter;
        if (importer != null)
        {
            importer.sRGBTexture = false; // 必须是 Linear
            importer.alphaSource = TextureImporterAlphaSource.FromInput;
            importer.textureCompression = TextureImporterCompression.Uncompressed; // 必须无压缩以保持精度
            importer.mipmapEnabled = false; // 不需要 Mipmap
            importer.filterMode = FilterMode.Point; // 点采样
            importer.wrapMode = TextureWrapMode.Clamp;
            importer.npotScale = TextureImporterNPOTScale.None;
            
            // 确保是 RGBA Float 格式
            TextureImporterPlatformSettings settings = importer.GetDefaultPlatformTextureSettings();
            settings.format = TextureImporterFormat.RGBAFloat;
            settings.textureCompression = TextureImporterCompression.Uncompressed;
            importer.SetPlatformTextureSettings(settings);

            importer.SaveAndReimport();
        }
    }

    // --- 数学帮助函数 (保持不变) ---

    static float MipmapLevelToPerceptualRoughness(float mipmapLevel)
    {
        float perceptualRoughness = Mathf.Clamp01(mipmapLevel / UNITY_SPECCUBE_LOD_STEPS);
        return Mathf.Clamp01(1.7f / 1.4f - Mathf.Sqrt(2.89f / 1.96f - (2.8f / 1.96f) * perceptualRoughness));
    }

    static float PerceptualRoughnessToRoughness(float perceptualRoughness)
    {
        return perceptualRoughness * perceptualRoughness;
    }

    static Vector2 Fibonacci2d(int i, int nbSamples)
    {
        const float GOLDEN_RATIO = 1.618033988749895f;
        float x = i / (float)nbSamples + (0.5f / nbSamples);
        float y = (i / GOLDEN_RATIO) - Mathf.Floor(i / GOLDEN_RATIO);
        return new Vector2(x, y);
    }

    static void SampleGGXDir(Vector2 u, float roughness, out Vector3 localL, out float NdotL, out float NdotH, out float LdotH)
    {
        float denominator = 1.0f + (roughness * roughness - 1.0f) * u.x;
        float cosTheta = Mathf.Sqrt(Mathf.Max(0.0001f, (1.0f - u.x) / denominator));
        float phi = 2.0f * Mathf.PI * u.y;

        float sinPhi = Mathf.Sin(phi);
        float cosPhi = Mathf.Cos(phi);
        float sinTheta = Mathf.Sqrt(Mathf.Max(0.0f, 1.0f - cosTheta * cosTheta));
        
        Vector3 localH = new Vector3(
            cosPhi * sinTheta,
            sinPhi * sinTheta,
            cosTheta
        );

        NdotH = cosTheta;

        Vector3 localV = new Vector3(0.0f, 0.0f, 1.0f);
        float VdotH = NdotH;

        localL = -localV + 2.0f * VdotH * localH;
        NdotL = localL.z;
        LdotH = VdotH;
    }

    static float ComputeOmegaS(float NdotH, float roughness, int sampleCount)
    {
        float a2 = roughness * roughness;
        float s = (NdotH * a2 - NdotH) * NdotH + 1.0f;
        float D_GGXNoPI = Mathf.Max(0.0001f, a2 / (s * s));
        float D_GGX = D_GGXNoPI / Mathf.PI;
        
        float pdf = 0.25f * D_GGX;
        float omegaS = 1.0f / (sampleCount * pdf);
        
        return omegaS;
    }
}
#endif